sonar.projectKey=RickaPrincy_wallio-api
sonar.projectName=wallio-api
sonar.organization=rickaprincy
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.minimum=80